export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const SELECT_PRODUCT_ERR = "SELECT_PRODUCT_ERR";

export const SELECT_FEATURE_PRODUCT = "SELECT_PRODUCT";
export const SELECT_FEATURE_PRODUCT_ERR = "SELECT_PRODUCT_ERR";

