export const FEATUREPRODUCT = "FEATUREPRODUCT";
export const FEATUREPRODUCT_ERR = "FEATUREPRODUCT_ERR";

export const DEALPRODUCT = "DEALPRODUCT";
export const DEALPRODUCT_ERR = "DEALPRODUCT_ERR";

export const ONSALEPRODUCT = "ONSALEPRODUCT";
export const ONSALEPRODUCT_ERR = "ONSALEPRODUCT_ERR";

export const BESTRATEDPRODUCT = "BESTRATEDPRODUCT";
export const BESTRATEDPRODUCT_ERR = "BESTRATEDPRODUCT_ERR";

