export const PRODUCT = "FEATUREPRODUCT";
export const PRODUCT_ERR = "FEATUREPRODUCT_ERR";

export const DEALPRODUCT = "DEALPRODUCT";
export const DEALPRODUCT_ERR = "DEALPRODUCT_ERR";

export const ADD_TOCART = "ADD_TOCART";
export const ADD_TOCART_ERR = "ADD_TOCART_ERR";

export const DELETE_PRODUCT_INCART = "DELETE_PRODUCT_INCART";
export const DELETE_PRODUCT_INCART_ERR = "DELETE_PRODUCT_INCART_ERR";

export const MESSAGE_CHANGE = "MESSAGE_CHANGE";
export const MESSAGE_CHANGE_ERR = "MESSAGE_CHANGE_ERR";
